url: https://joshsamara.github.io

# Site settings
title: Josh Samara
email: joshsamara@gmail.com
description: "This is Josh Samara's github portfolio website."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: feb736
  secondary: ffa400
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Josh Samara
  pic: 1
  position: Lead Designer
  social:
    - title: twitter
      url: https://twitter.com/JoshTSamara
    - title: facebook
      url: https://www.facebook.com/josh.t.samara
    - title: stack-overflow
      url: http://stackoverflow.com/users/4221170/josh-samara

- name: Josh Samara
  pic: 2
  position: Lead Marketer
  social:
    - title: twitter
      url: https://twitter.com/JoshTSamara
    - title: facebook
      url: https://www.facebook.com/josh.t.samara
    - title: linkedin
      url: https://www.linkedin.com/profile/view?id=382493882

- name: Josh Samara
  pic: 3
  position: Lead Developer
  social:
    - title: twitter
      url: https://twitter.com/JoshTSamara
    - title: facebook
      url: https://www.facebook.com/josh.t.samara
    - title: google-plus
      url: https://plus.google.com/100723427098700632774/

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/JoshTSamara
  - title: facebook
    url: https://www.facebook.com/josh.t.samara
  - title: stack-overflow
    url: http://stackoverflow.com/users/4221170/josh-samara
  - title: bitbucket
    url: http://bitbucket.org/joshsamara
  - title: github
    url: http://github.com/joshsamara

# Postal address (add as many lines as necessary)
address:
  - line: 600 Atlantic Ave. Floor 20
  - line: Boston, MA 02210

# Build settings
markdown: kramdown
permalink: pretty
